create_table_query_news = '''CREATE TABLE news
(ID SERIAL PRIMARY KEY,
NEWS_HEADER TEXT,
news_text TEXT,
NEWS_PUBLISH_DATE DATE,
NEWS_LINK TEXT);'''

create_table_query_media = '''CREATE TABLE media
(ID SERIAL PRIMARY KEY,
MEDIA_TYPE TEXT,
MEDIA_SOURCE TEXT,
MEDIA_RATE TEXT,
MEDIA_HEADING TEXT,
MEDIA_CIRCULATION TEXT);'''

create_table_query_geo = '''CREATE TABLE geo
(ID SERIAL PRIMARY KEY,
GEO_COUNTRY TEXT,
GEO_REGION TEXT,
GEO_CITY TEXT,
GEO_LINK TEXT);'''

query_all = '''SELECT *
FROM news'''